package com.opencamera.app

import androidx.annotation.StringRes
import com.opencamera.app.i18n.AppTextResolver
import com.opencamera.core.mode.ModeId
import com.opencamera.core.settings.CompositionGridMode
import com.opencamera.core.settings.CountdownDuration
import com.opencamera.core.settings.PersistedSettings
import com.opencamera.core.settings.StyleMoodDescriptor
import com.opencamera.core.settings.StylePresetFamily

open class TestAppTextResolver : AppTextResolver(null) {
    internal override fun get(@StringRes resId: Int): String = when (resId) {
        R.string.button_color_lab_entry -> "Color Lab"
        R.string.button_dev_entry -> "DEV"
        R.string.button_dev_restart_session -> "Restart Session"
        R.string.button_filter_close -> "Close Filter Lab"
        R.string.button_filter_entry -> "Tone Lab"
        R.string.button_low_light_night_prompt -> "Night"
        R.string.button_low_light_night_prompt_degraded -> "Night assist (single-frame)"
        R.string.button_low_light_night_prompt_disabled -> "Night assist off"
        R.string.button_low_light_night_prompt_enabled -> "Night assist on"
        R.string.button_more_controls -> "More"
        R.string.button_open_style_page -> "Open Style Page"
        R.string.button_palette_entry -> "Style"
        R.string.button_portrait_mode -> "Portrait Lab"
        R.string.button_quick_brightness -> "Brightness"
        R.string.button_quick_brightness_na -> "N/A"
        R.string.button_quick_flash -> "Quality"
        R.string.button_quick_grid -> "Grid"
        R.string.button_quick_launcher -> "Quick"
        R.string.button_quick_live -> "Live"
        R.string.button_quick_ratio -> "Ratio"
        R.string.button_quick_resolution -> "Size"
        R.string.button_quick_timer -> "Timer"
        R.string.button_quick_watermark -> "Watermark"
        R.string.button_restart_session -> "Restart Session"
        R.string.button_save_as_custom -> "Save as Custom"
        R.string.button_settings_close -> "Close Settings"
        R.string.button_settings_entry -> "Settings"
        R.string.button_shutter_short -> "Shutter"
        R.string.button_single_lens -> "Single Lens"
        R.string.button_still_12mp -> "Still 12MP"
        R.string.button_still_2mp -> "Still 2MP"
        R.string.button_still_8mp -> "Still 8MP"
        R.string.button_still_fast -> "Still Fast"
        R.string.button_still_max -> "Still Max"
        R.string.button_still_quality -> "Still Quality"
        R.string.button_still_quality_unavailable -> "Still N/A"
        R.string.button_still_resolution -> "Still Size"
        R.string.button_still_resolution_unavailable -> "Size N/A"
        R.string.button_stop_session -> "Stop Session"
        R.string.button_switch_lens -> "Switch Lens"
        R.string.button_switch_to_advanced -> "Switch to Advanced"
        R.string.button_switch_to_back -> "Switch to Back"
        R.string.button_switch_to_front -> "Switch to Front"
        R.string.button_switch_to_light -> "Switch to Light"
        R.string.button_tap_to_cycle -> "Tap to cycle"
        R.string.button_use_this_look -> "Use This Look"
        R.string.button_use_this_style -> "Use Style"
        R.string.button_use_this_template -> "Use This Template"
        R.string.button_watermark_style_short -> "Style"
        R.string.button_zoom_prefix -> "Zoom"
        R.string.button_zoom_unavailable -> "Zoom N/A"
        R.string.checkin_degraded_badge -> "Multi-frame unavailable"
        R.string.checkin_degraded_depth -> "Depth effect unavailable, using Focus mode"
        R.string.checkin_degraded_multiframe -> "Multi-frame unavailable, using best single-frame"
        R.string.checkin_focus_mode -> " | Focus mode"
        R.string.checkin_guidance_clarity -> "Tip: stay steady, multi-frame synthesis will enhance detail"
        R.string.checkin_guidance_object_place -> "Tip: focus on details, use ambient light to enhance texture"
        R.string.checkin_guidance_people_place -> "Tip: balance the person and environment, leave space for ambiance"
        R.string.checkin_guidance_portrait -> "Tip: keep the subject centered, use depth of field to highlight the focus"
        R.string.checkin_headline -> "Check-in Style"
        R.string.checkin_scenario_clarity -> "Clarity"
        R.string.checkin_scenario_desc_clarity -> "Multi-frame synthesis for sharper detail"
        R.string.checkin_scenario_desc_object_place -> "Objects with environment, capturing detail and space"
        R.string.checkin_scenario_desc_people_place -> "People combined with environment to capture atmosphere"
        R.string.checkin_scenario_desc_portrait -> "Close-up portrait highlighting expression and posture"
        R.string.checkin_scenario_object_place -> "Object & Place"
        R.string.checkin_scenario_people_place -> "People & Place"
        R.string.checkin_scenario_portrait -> "Portrait"
        R.string.checkin_scene_prefix -> "Scene: "
        R.string.checkin_scene_title -> "Scene"
        R.string.checkin_select_scene -> "Select"
        R.string.checkin_style_title -> "Style"
        R.string.checkin_use_style -> "Use"
        R.string.color_cool_muted -> "Cool/Muted"
        R.string.color_green_cool -> "Green/Cool"
        R.string.color_lab_panel_title -> "Color Lab"
        R.string.color_magenta_warm -> "Magenta/Warm"
        R.string.color_neutral -> "Neutral"
        R.string.dev_capture_prefix -> "Capture: "
        R.string.dev_close -> "Close"
        R.string.dev_export_log -> "Export Log"
        R.string.dev_last_issue_prefix -> " | Last issue: "
        R.string.dev_last_timing_prefix -> " | Last timing: "
        R.string.dev_link_timing_header -> "--- Link Timing ---"
        R.string.dev_mode_prefix -> "Mode: "
        R.string.dev_recording_prefix -> "Recording: "
        R.string.dev_slowest_timing_prefix -> " | Slowest timing: "
        R.string.dev_status_prefix -> "Status: "
        R.string.dev_tab_all -> "All"
        R.string.dev_tab_core -> "Pipeline"
        R.string.dev_tab_error -> "Error"
        R.string.dev_tab_key -> "Summary"
        R.string.disabled_brightness_active_shot -> "Wait for current capture to finish"
        R.string.disabled_brightness_countdown -> "Wait for countdown to finish"
        R.string.disabled_brightness_unsupported -> "Brightness unavailable"
        R.string.disabled_countdown -> "Countdown in progress"
        R.string.disabled_frame_ratio_active_shot -> "Wait for current capture to finish"
        R.string.disabled_frame_ratio_countdown -> "Wait for countdown to finish"
        R.string.disabled_frame_ratio_unsupported_mode -> "Frame ratio not supported in current mode"
        R.string.disabled_live_photo_unsupported_mode -> "Live photo is not supported in current mode"
        R.string.disabled_permission -> "Camera permission required"
        R.string.disabled_preparing_recording -> "Preparing to record"
        R.string.disabled_preset_switching_recording -> "Preset switching unavailable during recording"
        R.string.disabled_preview_recovering -> "Camera recovering"
        R.string.disabled_recording -> "Unavailable during recording"
        R.string.disabled_saving_photo -> "Saving previous photo"
        R.string.disabled_stopping_recording -> "Stopping and saving"
        R.string.disabled_zoom_unavailable -> "Zoom unavailable"
        R.string.document_batch_crop_applied -> "Cropped"
        R.string.document_batch_crop_failed -> "Crop failed"
        R.string.document_batch_crop_skipped -> "Not cropped"
        R.string.document_batch_move_down -> "Move down"
        R.string.document_batch_move_up -> "Move up"
        R.string.document_batch_organizer_title -> "Organize Batch"
        R.string.document_batch_remove -> "Remove from batch"
        R.string.button_document_batch_continue_shooting -> "Continue Shooting"
        R.string.button_document_batch_crop_edit -> "Enter Crop Edit"
        R.string.button_document_batch_crop_edit_coming_soon -> "Crop Edit Coming Soon"
        R.string.document_crop_edit_title -> "Crop Edit"
        R.string.document_crop_edit_confirm -> "Confirm"
        R.string.document_crop_edit_cancel -> "Cancel"
        R.string.document_crop_edit_page_format -> "Page %d"
        R.string.document_crop_edit_marked_manual -> "Marked as cropped"
        R.string.button_document_batch_export -> "Export Batch"
        R.string.document_export_progress -> "Exporting %d/%d pages"
        R.string.document_export_success -> "Export success, %d pages"
        R.string.document_export_failed -> "Export failed"
        R.string.button_document_export_return -> "Return to Shooting"
        R.string.button_document_export_retry -> "Retry"
        R.string.document_batch_empty_hint -> "No pages yet, tap Continue Shooting to start"
        R.string.error_microphone_unavailable -> "Microphone capture unavailable on this device"
        R.string.error_no_compatible_filters -> "No compatible filters"
        R.string.error_no_watermark_templates -> "No watermark templates available"
        R.string.error_still_capture_unavailable -> "Still capture unavailable on this device"
        R.string.error_video_recording_unavailable -> "Video recording unavailable on this device"
        R.string.filter_adjustment_high -> "High"
        R.string.filter_adjustment_low -> "Low"
        R.string.filter_adjustment_medium -> "Medium"
        R.string.filter_adjustment_off -> "Off"
        R.string.filter_ctrl_cool_boost -> "Cool Boost"
        R.string.filter_ctrl_exposure -> "Exposure"
        R.string.filter_ctrl_grain -> "Grain"
        R.string.filter_ctrl_halo -> "Halo"
        R.string.filter_ctrl_highlights -> "Highlights"
        R.string.filter_ctrl_shadows -> "Shadows"
        R.string.filter_ctrl_sharpness -> "Sharpness"
        R.string.filter_ctrl_soft_glow -> "Soft Glow"
        R.string.filter_ctrl_temp_shift -> "Temp Shift"
        R.string.filter_ctrl_tint_shift -> "Tint Shift"
        R.string.filter_ctrl_vignette -> "Vignette"
        R.string.filter_ctrl_warm_boost -> "Warm Boost"
        R.string.filter_family_humanistic -> "Humanistic"
        R.string.filter_family_photo -> "Photo"
        R.string.filter_family_portrait -> "Portrait"
        R.string.filter_family_video -> "Video"
        R.string.filter_lab_drag_to_create_custom -> "Drag palette to save as custom"
        R.string.filter_lab_editing_disabled -> "Finish the current capture before changing filter defaults."
        R.string.filter_lab_editing_enabled -> "Selected family defaults save instantly and refresh the active mode when relevant."
        R.string.filter_lab_footer -> "Independent Tone Lab prioritized. Panel adjustments and custom saves ongoing; import/export deferred."
        R.string.filter_lab_color_summary -> "Color Lab edits a live color wash over the current mode: warm/cool runs left to right, tone depth runs top to bottom."
        R.string.filter_lab_color_hint -> "Horizontal swipe adjusts warmth and tint; vertical swipe controls lift or deep contrast."
        R.string.filter_lab_light_palette_hint -> "Horizontal swipe for color, vertical swipe for tone."
        R.string.filter_lab_save_custom_already_custom -> "Unavailable • Current default already custom"
        R.string.filter_lab_save_custom_unavailable_profile -> "Unavailable • Missing source profile"
        R.string.filter_lab_selected_default -> " | Selected default"
        R.string.filter_lab_supporting_text -> "Independent filter panel for mode defaults. Import and export stay deferred in this closure; selected looks can be adjusted or saved as custom."
        R.string.filter_light_palette_color -> "Color"
        R.string.filter_light_palette_tone -> "Tone"
        R.string.filter_section_palette -> "Palette"
        R.string.filter_signed_cool -> "Cool"
        R.string.filter_signed_cool_plus -> "Cool+"
        R.string.filter_signed_green -> "Green"
        R.string.filter_signed_green_plus -> "Green+"
        R.string.filter_signed_magenta -> "Magenta"
        R.string.filter_signed_magenta_plus -> "Magenta+"
        R.string.filter_signed_off -> "Off"
        R.string.filter_signed_warm -> "Warm"
        R.string.filter_signed_warm_plus -> "Warm+"
        R.string.label_aperture -> "Aperture"
        R.string.label_audio_scene -> "Audio scene"
        R.string.label_auto -> "Auto"
        R.string.label_background -> "Background"
        R.string.label_beauty_preset -> "Beauty preset"
        R.string.label_beauty_strength -> "Beauty strength"
        R.string.label_bokeh_effect -> "Bokeh effect"
        R.string.label_color -> "Color"
        R.string.label_composition_grid -> "Composition grid"
        R.string.label_countdown -> "Countdown"
        R.string.label_default_photo_filter -> "Default photo filter"
        R.string.label_dynamic_fps -> "Dynamic fps"
        R.string.label_ev -> "EV"
        R.string.label_focus -> "Focus"
        R.string.label_frame_background -> "Frame background"
        R.string.label_frame_rate -> "Frame rate"
        R.string.label_frame_ratio_title -> "Frame"
        R.string.label_iso -> "ISO"
        R.string.label_language_restart_hint -> "Restart app to apply"
        R.string.label_language_setting -> "Language"
        R.string.label_live_photo_default -> "Live photo default"
        R.string.label_live_save_format -> "Live save format"
        R.string.label_opacity -> "Opacity"
        R.string.label_placement -> "Placement"
        R.string.label_portrait_lab -> "Portrait Lab"
        R.string.label_portrait_profile -> "Portrait profile"
        R.string.label_raw -> "RAW"
        R.string.label_resolution -> "Resolution"
        R.string.label_scale -> "Scale"
        R.string.label_selfie_mirror -> "Selfie mirror"
        R.string.label_shutter -> "Shutter"
        R.string.label_shutter_tone -> "Shutter tone"
        R.string.label_text_opacity -> "Text opacity"
        R.string.label_text_placement -> "Text placement"
        R.string.label_text_scale -> "Text scale"
        R.string.label_tokens -> "Tokens"
        R.string.label_tone -> "Tone"
        R.string.label_video_filter_seed -> "Video filter seed"
        R.string.label_watermark_lab -> "Watermark Lab"
        R.string.label_wb -> "WB"
        R.string.lens_back -> "Back"
        R.string.lens_front -> "Front"
        R.string.lens_lab_editing_disabled -> "Finish the current capture before changing saved defaults."
        R.string.lens_lab_editing_enabled -> "Changes save instantly and refresh the active mode defaults."
        R.string.level_cool -> "Cool"
        R.string.level_cool_plus -> "Cool+"
        R.string.level_green -> "Green"
        R.string.level_green_plus -> "Green+"
        R.string.level_magenta -> "Magenta"
        R.string.level_magenta_plus -> "Magenta+"
        R.string.level_warm -> "Warm"
        R.string.level_warm_plus -> "Warm+"
        R.string.live_photo_asset_motion -> "Motion"
        R.string.live_photo_asset_sidecar -> "Sidecar"
        R.string.live_photo_asset_still -> "Still"
        R.string.live_photo_asset_thumbnail -> "Thumbnail"
        R.string.low_light_night_assist_content_description -> "Low-light night assist prompt"
        R.string.manual_adapter_applies -> "Adapter applies"
        R.string.manual_camera2_interop -> "Camera2 interop"
        R.string.manual_controls_unavailable -> "Manual controls currently unavailable"
        R.string.manual_saved_only -> "Saved only"
        R.string.manual_stay_saved_only -> "stay saved-only"
        R.string.manual_temporarily_unsupported -> "Temporarily unsupported"
        R.string.manual_temporarily_unsupported_suffix -> "temporarily unsupported"
        R.string.output_error_prefix -> "Camera issue:"
        R.string.output_live_prefix -> "Last Live photo:"
        R.string.output_preview_prefix -> "Preview thumbnail:"
        R.string.output_saved_prefix -> "Last photo:"
        R.string.output_video_prefix -> "Last video:"
        R.string.output_waiting -> "No photo captured yet."
        R.string.permission_camera_only -> "Camera granted. Video recording will be silent until microphone permission is granted."
        R.string.permission_denied -> "Camera permission denied. Tap shutter to request it again."
        R.string.permission_granted -> "Camera permission granted. Preview is ready."
        R.string.permission_open_settings -> "Open Settings"
        R.string.permission_pending -> "Camera permission is required before preview can start."
        R.string.permission_permanently_denied -> "Camera permission permanently denied. Please enable it in system settings."
        R.string.portrait_lab_editing_disabled -> "Finish the current capture before changing portrait product defaults."
        R.string.portrait_lab_editing_enabled -> "Portrait defaults save instantly and apply to the next portrait capture metadata and lightweight render pass."
        R.string.portrait_lab_footer -> "Tone Lab still owns portrait color style selection. Portrait Lab only governs the product profile, beauty plan/strength, and lightweight bokeh rendering metadata introduced in 6B-5."
        R.string.portrait_lab_joiner_beauty -> "Beauty "
        R.string.portrait_lab_joiner_bokeh -> "Bokeh "
        R.string.portrait_lab_supporting -> "Portrait product controls sit one level below Settings. Use this page to adjust the saved portrait profile, beauty behavior, and bokeh effect without changing the active portrait filter roster."
        R.string.pro_controls_default -> "Professional Controls"
        R.string.pro_controls_finish_capture_hint -> "Finish the current capture before editing."
        R.string.pro_controls_humanistic -> "Humanistic Professional Controls"
        R.string.pro_controls_supporting_editable -> "Upper-layer manual draft is currently editable; each control indicates its status: Applied, Saved-only, or Temporarily unsupported."
        R.string.pro_controls_supporting_readonly -> "Draft changes allowed, but this device currently holds all controls in saved-only or temporarily-unsupported state."
        R.string.raw_saved_only_value -> "Record only"
        R.string.settings_action_unsupported -> "Action not supported in current mode"
        R.string.settings_blocked_by_capture -> "Capture in progress, settings locked"
        R.string.settings_joiner_filter -> "Filter "
        R.string.settings_joiner_grid -> "Grid "
        R.string.settings_joiner_live -> " | Live "
        R.string.settings_joiner_mic -> " | Mic "
        R.string.settings_joiner_portrait -> " | Portrait "
        R.string.settings_joiner_selfie_mirror -> " | Selfie mirror "
        R.string.settings_joiner_shutter_sound -> " | Shutter sound "
        R.string.settings_joiner_timer -> " | Timer "
        R.string.settings_joiner_watermark -> " | Watermark "
        R.string.settings_not_loaded -> "Settings not loaded yet"
        R.string.settings_page_portrait_support -> "Open profile + beauty + bokeh tuning"
        R.string.settings_page_pro_manual_prefix -> " | Humanistic manual draft "
        R.string.settings_page_supporting -> "Quick defaults with explicit supported, degraded, and staged capability hints."
        R.string.settings_section_common -> "General"
        R.string.settings_section_photo -> "Photo"
        R.string.settings_section_video -> "Video"
        R.string.settings_summary_filter -> "Filter"
        R.string.settings_summary_filters -> "filters"
        R.string.settings_summary_grid -> "Grid"
        R.string.settings_summary_live -> "Live"
        R.string.settings_summary_mic -> "Mic"
        R.string.settings_summary_ms_bundle -> "ms bundle"
        R.string.settings_summary_portrait -> "Portrait"
        R.string.settings_summary_pro_manual_draft -> "Humanistic manual draft"
        R.string.settings_summary_selfie_mirror -> "Selfie mirror"
        R.string.settings_summary_shutter_sound -> "Shutter sound"
        R.string.settings_summary_timer -> "Timer"
        R.string.settings_summary_watermark -> "Watermark"
        R.string.settings_summary_watermark_templates -> "watermark templates"
        R.string.status_current_default -> "Current default"
        R.string.status_custom -> "Custom"
        R.string.status_custom_badge -> " | Custom"
        R.string.status_no_compatible_looks -> "No compatible looks"
        R.string.status_pro_active -> "Pro active"
        R.string.status_processing_photo_keep_open -> "Processing photo. Please keep OpenCamera open."
        R.string.status_ready_becomes_default -> "Ready • Becomes the default"
        R.string.status_ready_editing_custom -> "Ready • Editing current custom look"
        R.string.status_recording_active -> "Recording"
        R.string.status_recording_saving -> "Saving…"
        R.string.status_recording_starting -> "Starting…"
        R.string.status_renderer_pending -> "Renderer pending"
        R.string.status_selected_default -> "Selected default"
        R.string.status_unavailable_already_custom -> "Unavailable • Current default already custom"
        R.string.status_unavailable_missing_profile -> "Unavailable • Missing source profile"
        R.string.style_panel_title -> "Style"
        R.string.tone_balanced -> "Balanced"
        R.string.tone_deep_contrast -> "Deep Contrast"
        R.string.tone_soft_lift -> "Soft Lift"
        R.string.video_locked_fps -> "Locked fps"
        R.string.video_low_light_auto -> "Low-light auto 24fps"
        R.string.watermark_attr_background_prefix -> "Background "
        R.string.watermark_attr_opacity_prefix -> "Opacity "
        R.string.watermark_attr_placement_prefix -> "Placement "
        R.string.watermark_attr_scale_prefix -> "Scale "
        R.string.watermark_detail_editing_disabled -> "Finish the current capture before changing watermark styles."
        R.string.watermark_detail_editing_enabled -> "Template-specific styles save instantly and stay attached to this watermark preset."
        R.string.watermark_detail_footer_frame -> "Frame border rendering is live for static-photo export."
        R.string.watermark_detail_footer_overlay -> "Classic overlay stays inside the source image without an expanded border."
        R.string.watermark_detail_footer_pure_text -> "A translucent blue bottom bar stays inside the source image with a small warm light accent."
        R.string.watermark_detail_supporting_not_selected -> "This template is not yet the current default. Adjust here first, then switch from the selector page when ready."
        R.string.watermark_detail_supporting_selected -> "This is the active default watermark. Changes here will affect the next static photo rendered with this template."
        R.string.watermark_detail_tokens_prefix -> "Tokens: "
        R.string.watermark_selector_current_default -> " | Current default"
        R.string.watermark_selector_default_prefix -> "Default "
        R.string.watermark_selector_edit_attrs_classic -> "Placement, scale, opacity"
        R.string.watermark_selector_edit_attrs_frame -> "Placement, scale, opacity, background"
        R.string.watermark_selector_editing_disabled -> "Finish the current capture before changing watermark defaults."
        R.string.watermark_selector_editing_enabled -> "Default template changes save instantly. Each template keeps its own placement, scale, opacity, and frame background preset."
        R.string.watermark_selector_footer_supported -> "Classic Overlay keeps its border background fixed; Travel Polaroid and Retro Frame expose frame background variants on their own style pages. All still-photo watermarks embed a reversible original JPEG archive, extractable via the provided tooling."
        R.string.watermark_selector_footer_unsupported -> "Still capture is unavailable on this device, so Watermark Lab stays read-only."
        R.string.watermark_selector_supporting -> "Watermark selection sits one level below Settings. Pick the active template here, then enter the template-specific style page to edit."
        R.string.watermark_template_blur_four_border -> "Blur four border"
        R.string.watermark_template_blue_hour -> "Blue Hour"
        R.string.watermark_template_classic_overlay -> "Classic overlay"
        R.string.watermark_template_expanded_frame -> "Expanded frame"
        R.string.watermark_template_pure_text -> "Translucent Bottom Bar"
        R.string.watermark_template_retro_frame -> "Retro Frame"
        R.string.watermark_template_travel_polaroid -> "Travel Polaroid"
        R.string.watermark_template_van_gogh_starry -> "Van Gogh Starry"
        R.string.watermark_token_camera_params -> "Camera Params"
        R.string.watermark_token_datetime -> "Date/Time"
        R.string.watermark_token_location -> "Location"
        R.string.watermark_token_model -> "Model"
        else -> super.get(resId)
    }
    override fun modeDisplayName(modeId: ModeId): String = when (modeId) {
        ModeId.PHOTO -> "Photo"
        ModeId.CHECK_IN -> "Check-in"
        ModeId.DOCUMENT -> "Doc"
        ModeId.HUMANISTIC -> "Humanistic"
        ModeId.VIDEO -> "Video"
    }

    override fun modeTrackLabel(modeId: ModeId): String = modeDisplayName(modeId)

    override fun gridModeLabel(value: CompositionGridMode): String = when (value) {
        CompositionGridMode.OFF -> "Off"
        CompositionGridMode.RULE_OF_THIRDS -> "3x3"
        CompositionGridMode.GOLDEN_RATIO -> "Golden"
    }

    override fun countdownLabel(value: CountdownDuration): String = when (value) {
        CountdownDuration.OFF -> "Off"
        CountdownDuration.SECONDS_3 -> "3s"
        CountdownDuration.SECONDS_5 -> "5s"
        CountdownDuration.SECONDS_10 -> "10s"
    }

    override fun onOff(enabled: Boolean): String = if (enabled) "On" else "Off"
    internal override fun styleRailTitle(family: FilterLabFamily): String = when (family) {
        FilterLabFamily.PHOTO -> "Photo Styles"
        FilterLabFamily.HUMANISTIC -> "Humanistic Styles"
        FilterLabFamily.PORTRAIT -> "Portrait Styles"
        FilterLabFamily.VIDEO -> "Video Styles"
        FilterLabFamily.DOCUMENT -> "文档色彩"
    }
    internal override fun styleRailSupportingText(family: FilterLabFamily): String = when (family) {
        FilterLabFamily.PHOTO -> "Tap a card to apply this look instantly."
        FilterLabFamily.HUMANISTIC -> "Street and life presets for a human perspective."
        FilterLabFamily.PORTRAIT -> "Portrait-specific tone presets."
        FilterLabFamily.VIDEO -> "Video look presets applied before recording."
        FilterLabFamily.DOCUMENT -> "选择文档色彩模式"
    }
    override fun filterLabHeroSummary(familyLabel: String, filterLabel: String, count: Int): String = "$familyLabel default $filterLabel • $count looks staged"
    override fun filterLabCurrentDefault(filterLabel: String): String = "Current default $filterLabel"
    override fun filterLabNextLook(familyLabel: String): String = "Next $familyLabel look"
    override fun filterLabLooksDeferred(count: Int): String = "$count looks | import/export deferred"
    override fun filterLabSaveCustomReady(familyLabel: String): String = "Ready • Becomes the $familyLabel default"
    override fun devLogTitleKey(count: Int): String = "Summary Log ($count)"
    override fun devLogTitleCore(count: Int): String = "Pipeline Log ($count)"
    override fun devLogTitleError(count: Int): String = "Error Log ($count)"
    override fun devLogTitleAll(count: Int): String = "All Events ($count)"
    override fun devLogTitleLink(count: Int): String = "Link Flow ($count)"
    override fun liveSaveFormatSupportLabel(count: Int): String = "$count formats: Motion Photo, MP4 Sidecar, JPEG Only"
    override fun livePhotoDefaultSupportLabel(motionDurationMs: Int): String = "Toggle default; $motionDurationMs ms motion bundle"
    override fun zoomRatioLabel(ratio: Float): String = "${ratio}x"
    override fun countdownSeconds(seconds: Int): String = "${seconds}s"
    override fun outputSizeLabel(width: Int, height: Int): String = "${width}x${height}"
    override fun kelvinLabel(k: Int): String = "${k}K"
    override fun shutterSpeedMs(ms: Int): String = "${ms}ms"
    override fun focusDistanceDiopters(d: Float): String = java.lang.String.format("%.1fD", d)
    override fun apertureFNumber(f: Float): String = java.lang.String.format("f/%s", f)
    override fun supportCount(count: Int): String = "$count options"
    override fun looksCount(count: Int): String = "$count curated looks"
    override fun templatesCount(count: Int): String = "$count templates"
    override fun presetsCount(count: Int): String = "$count presets"
    override fun placementsCount(count: Int): String = "$count placements"
    override fun stepsCount(count: Int): String = "$count steps"
    override fun levelsCount(count: Int): String = "$count levels"
    override fun moodsCount(count: Int): String = "$count moods"
    override fun productProfilesCount(count: Int): String = "$count product profiles"
    override fun plansCount(count: Int): String = "$count plans"
    override fun renderingFeelsCount(count: Int): String = "$count rendering feels"
    override fun nextLookLabel(label: String): String = "Next $label look"

    // Settings joiners

    // Settings page
    override fun gridSupportLabel(count: Int): String = "Cycle $count layouts"
    override fun watermarkTuningLabel(count: Int): String = "Open selector + per-template tuning; $count templates"
    override fun liveSupportLabel(durationMs: Int, watermarkBehavior: String): String = "Saved default only; $durationMs ms bundle | dynamic watermark $watermarkBehavior"
    override fun degradedResolutionLabel(saved: String, active: String): String = "Saved as $saved, active graph uses $active"
    override fun degradedFramerateLabel(saved: String, active: String): String = "Saved as $saved, active graph uses $active"
    override fun degradedDynamicFpsLabel(saved: String, active: String): String = "Saved as $saved, active graph uses $active"
    override fun degradedAudioLabel(saved: String, active: String): String = "Saved as $saved, active graph uses $active"
    override fun videoFilterSeedCountLabel(count: Int): String = "Saved filter seed; $count looks staged"

    // Watermark selector
    override fun watermarkSelectorTemplatesStaged(count: Int): String = " templates staged"

    // Watermark detail

    // Watermark attribute prefixes

    // Check-in style panel
    override fun checkInEditingHint(enabled: Boolean): String = if (enabled) "Tap to select scene and style" else "Capturing, cannot switch"
    override fun zoomSliderDescription(ratio: Float, disabledReason: String?): String = if (disabledReason != null) "Zoom: $disabledReason" else String.format("Zoom: %.1fx", ratio)

    override fun styleCardTitle(profileId: String, family: StylePresetFamily): String = when (profileId) {
        "photo-vivid" -> "鲜明"
        "photo-original" -> "原色"
        "photo-chasing-light" -> "追光"
        "photo-rich" -> "浓郁"
        "photo-texture" -> "质感"
        "photo-bw" -> "黑白"
        "humanistic-original" -> "人文原色"
        "humanistic-vivid" -> "人文鲜明"
        "humanistic-street" -> "街头"
        "humanistic-portrait" -> "人文人像"
        "humanistic-life" -> "生活"
        "portrait-blue" -> "冷调人像"
        "portrait-retro" -> "复古人像"
        "portrait-ccd" -> "CCD 人像"
        "portrait-vivid" -> "鲜明人像"
        "portrait-original" -> "原色人像"
        "portrait-chasing-light" -> "追光人像"
        "portrait-rich" -> "浓郁人像"
        else -> super.styleCardTitle(profileId, family)
    }

    override fun styleCardMoodLabel(descriptor: StyleMoodDescriptor): String = when {
        descriptor.isBw -> "黑白"
        descriptor.isMonochrome -> "单色"
        descriptor.isNatural -> "自然"
        descriptor.activeFlags().isEmpty() -> "自然"
        else -> {
            val zhParts = mutableListOf<String>()
            if (descriptor.isVivid) zhParts.add("鲜明")
            if (descriptor.isMuted) zhParts.add("柔和")
            if (descriptor.isPunchy) zhParts.add("明快")
            if (descriptor.isSoft) zhParts.add("柔焦")
            if (descriptor.isWarm) zhParts.add("暖色")
            if (descriptor.isCool) zhParts.add("冷色")
            if (descriptor.isFilm) zhParts.add("胶片")
            zhParts.joinToString("")
        }
    }

    // Portrait lab

    // Pro controls

    // Disabled reasons

    // Frame ratio control

    // Processing status

    // Recording status

    // Settings blocked

    // Color lab summary
    override fun colorToneSummary(colorAxis: Float, toneAxis: Float): String {
        val colorLabel = when {
            colorAxis > 0.6f -> "Warm+"
            colorAxis > 0.08f -> "Warm"
            colorAxis < -0.6f -> "Cool+"
            colorAxis < -0.08f -> "Cool"
            else -> "Neutral"
        }
        val toneLabel = when {
            toneAxis > 0.08f -> "Soft Lift"
            toneAxis < -0.08f -> "Deep Contrast"
            else -> "Balanced"
        }
        return "$colorLabel / $toneLabel"
    }

    override fun availabilityLabel(value: SettingsControlAvailability): String = when (value) {
        SettingsControlAvailability.SUPPORTED -> "可用"
        SettingsControlAvailability.DEGRADED -> "部分支持"
        SettingsControlAvailability.UNSUPPORTED -> "不支持"
    }
    override fun languageDisplayName(settings: PersistedSettings): String = "English"

    override fun sessionUiStrings(): SessionUiStrings {
        return SessionUiStrings(
            buttonSwitchToFront = "Switch to Front",
            buttonSwitchToBack = "Switch to Back",
            buttonSingleLens = "Single Lens",
            buttonZoomPrefix = "Zoom",
            buttonZoomUnavailable = "Zoom N/A",
            buttonStillFast = "Still Fast",
            buttonStillMax = "Still Max",
            buttonStillQualityUnavailable = "Still N/A",
            buttonStill12Mp = "Still 12MP",
            buttonStill8Mp = "Still 8MP",
            buttonStill2Mp = "Still 2MP",
            buttonStillResolutionUnavailable = "Size N/A",
            outputErrorPrefix = "Camera issue:",
            outputVideoPrefix = "Last video:",
            outputLivePrefix = "Last Live photo:",
            outputSavedPrefix = "Last photo:",
            outputPreviewPrefix = "Preview thumbnail:",
            outputWaiting = "No photo captured yet."
        )
    }

    open fun documentBatchOrganizerTitle(): String = "Organize Batch"
    open fun documentBatchRemoveLabel(): String = "Remove from batch"
    open fun documentBatchMoveUpLabel(): String = "Move up"
    open fun documentBatchMoveDownLabel(): String = "Move down"
}
